Optime\TriviaBundle\Entity\BaseTriviaAnswer:
  type: entity
  repositoryClass: Optime\TriviaBundle\Entity\repository\BaseTriviaAnswerRepository
  table: optime_trivia_user_answer
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    points:
      type: integer
      length: 255
    percent_correct:
      type: integer
    num_correct:
      type: integer
      nullable: true
    num_wrong:
      type: integer
      nullable: true
    num_empty:
      type: integer
      nullable: true
    createdAt:
      type: datetime
      column: created_at
    updatedAt:
      type: datetime
      column: updated_at
  manyToOne:
    trivia:
      targetEntity: Optime\TriviaBundle\Entity\BaseTrivia
      inversedBy: triviaAnswers