Optime\TriviaBundle\Entity\BaseUser:
  type: entity
  table: optime_user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  oneToMany:
    triviaAnswers:
      targetEntity: Optime\TriviaBundle\Entity\BaseTriviaAnswer
      mappedBy: user