services:
  Optime\TriviaBundle\Service\PresentationActions:
    class: Optime\TriviaBundle\Service\PresentationActions
    public: true
    arguments:
      $entityManager: "@doctrine.orm.entity_manager"
      $currentUser: "@=service('security.token_storage').getToken().getUser()"